# Background material

## Set theory

### Basic definitions

::: {.definition}
A *set* is just a collection of things. The things a set contains can be any
mathematical object and are called its *elements*. We will denote sets with
capital letters like $A$, $B$, $X$ and $Y$ and elements of sets with lowercase
letters like $a$, $b$, $x$ and $y$. If $a$ is an element of the set $A$ we will
write $a \in A$ and if $a$ is not an element of the set $A$ we will write $a
\notin A$.
:::

There are a number of ways one can define a set. If a set is finite, we can just
enumerate all of its elements, like this

$$
A = \{1, 2, 3, 4, 5, 6, 7\}.
$$

A set with an infinite number of elements can be defined by enumerating enough
of its elements to indicate a pattern among them and then placing an ellipsis
($\ldots$) at either end of the list to indicate that the list continues
forever, for example

$$
B = \{0, 3, 6, 9, \ldots\}.
$$

A set with an infinite size can also be defined by specifying a characteristic
property that all of its elements have. For example

$$
C = \{x | x \text{ is even}\}.
$$

::: {.definition}
The *size* of a set $A$, also referred to as the *cardinality* of the set, is
the number of elements in the set and is denoted by $|A|$. The size of a set can
be either finite or infinite.
:::

In the examples above, $|A| = 7$ and $|B| = |C| = \infty$. There is one special
set that contains no elements and whose size is zero, It is called the *empty
set* and is denoted by the symbol $\emptyset$. If we are to define it using the
notation above, $\emptyset = \{\}$.

::: {.definition}
Given two sets $A$ and $B$, it can happen that every element of $A$ is an
element of $B$. In this case we say that $A$ is a *subset* of $B$ and we write
$A \subseteq B$. If $A$ is a subset of $B$, but it is not equal to $B$, we say
that $A$ is a *proper subset* of $B$ and write $A \subset B$.
:::

Examples.

1. The empty set is a subset of *any* other set $A$, i.e. $\emptyset \subseteq
   A$.
2. Any set is a subset of itself, $A \subseteq A$.
3. $\{a,b\} \subset \{a,b,c,d,e\}$.
4. $\{0,2,4,6,\ldots\} \subset \{0,1,2,3,\ldots\}$.

### Operations on sets

Let $A$ and $B$ be two sets. We can form a number of other sets from the
elements of $A$ and $B$ via the following operations.

- The *union* of $A$ and $B$ is the set containing both the elements of $A$ and
  $B$:

  $$
  A \cup B \overset{\text{def}}{=} \{x | x \in A \text{ or } x \in B\}.
  $$

- The *intersection* of $A$ and $B$ is the set containing the common elements of
  $A$ and $B$:

  $$
  A \cap B \overset{\text{def}}{=} \{x | x \in A \text{ and } x \in B\}.
  $$

- The *difference* of $A$ and $B$ is the set of all elements in $A$ that are
  *not* in $B$:

  $$
  A \setminus B \overset{\text{def}}{=} \{x | x \in A \text{ and } x \notin B\}.
  $$

- If $B \subset A$, then the *complement* of $B$ is the set of all elements in
  $A$ that are not in $B$:

  $$
  \bar{B} \overset{\text{def}}{=} \{a | a \in A \text{ and } a \notin B \}.
  $$

- The *Cartesian product* of $A$ and $B$ is the set of all *ordered* pairs of
  elements, the first one being from $A$ and the second from $B$:

$$
A \times B \overset{\text{def}}{=} \{(a,b) | a \in A \text{ and } b \in B\}.
$$


Below are listed some commonly used sets and the letters used to denote them.
They are represented using the so called blackboard bold typeface.

1. $\mathbb{N} = \{0,1,2,\ldots\}$ is the set of natural numbers.
2. $\mathbb{Z} = \{\ldots,-2,-1,0,1,2,\ldots\}$ is the set of integers.
3. $\mathbb{Q} = \{x | x=\frac{p}{q}, \text{ where } p,q \in \mathbb{Z} \text{
   and } q \neq 0\}$ is the set of rational numbers.
4. $\mathbb{R}$ is the set of real numbers.
5. $\mathbb{R} \setminus \mathbb{Q}$ is the set of irrational numbers, e.g.
   $\pi, e, \sqrt 2$ etc.
6. $\mathbb{C}$ is the set of complex numbers.

We have the following subset inclusions among the sets above: $\mathbb{N}
\subset \mathbb{Z} \subset \mathbb{Q} \subset \mathbb{R} \subset \mathbb{C}.$

## Functions

## Polynomials

::: {.definition}
A *polynomial* is an expression of the form

$$
P(x) = a_nx^n + a_{n-1}x^{n-1} + \ldots a_1x + a_0.
$$

Here $x$ is considered to be a variable that can take any value and the $a_i$s
are arbitrary real numbers called the *coefficients* of the polynomial. Each of
the summands $a_ix^i$ is called a *term* of the polynomial. The exponent of $x$
in a term is called the *degree* of the term and the degree of the polynomial is
the largest degree among its terms with non-zero coefficient.
:::

Some examples of polynomials are:

1. $P_1(x) = c$, where $c \in \mathbb{R}$, a constant polynomial with $\deg{P_1}
   = 0$.
2. $P_2(x) = 3x - 5$, a linear polynomial with $\deg{P_2} = 1$.
3. $P_2(x) = x^2 -3x + 2$, a quadratic polynomial with $\deg{P_2} = 2$.
4. $P_3(x) = x^3 - 4x^2 + 5x + 2$, a cubic polynomial with $\deg{P_3} = 3$.

::: {.remark}
The zero polynomial $P(x) = 0$ is somewhat special. Even though it looks like a
constant polynomial of degree $0$, its degree is undefined as it has no non-zero
terms.
:::

::: {.definition}
A *root* of a polynomial $P(x)$ is a solution of the equation $P(x) = 0$, i.e. a
real number $a$ such that $P(a) = 0$.
:::

For polynomials of low degree, there are explicit formulas for their roots.

1. Degree $0$ polynomials have no roots. If $P(x) = c$ and $c \neq 0$, then
   there is no $x$ which can satisfy the equation $P(x) = 0$.
2. Degree $1$ polynomials are trivial. If $P(x) = ax + b$, then provided $a \neq
   0$ there is a single root given by $x = -\frac{b}{a}$. If $b = 0$, the root
   is $x = 0$.
3. Degree $2$ polynomials can be solved using the quadratic formula. If $P(x) =
3. ax^2 + bx + c$, then the two roots $x_1$ and $x_2$ of $P$ are given by:
$$
x_{1,2} = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}.
$$
The quantity $\Delta = b^2 - 4ac$ is called the *discriminant* of the quadratic
polynomial. Depending on whether the discriminant is positive, negative or zero
we can have the following cases:

    1. $\Delta > 0$, then $P$ has two different real roots.
    2. $\Delta = 0$, then $P$ has one double real root.
    3. $\Delta < 0$, then $P$ has two complex roots which are complex conjugate.

Examples.

1. Let $P(x) = x^2 - 3x + 2$. If we compute its discriminant we get $\Delta = 1
   > 0$ so we expect to have two different real roots. Indeed, we can factor $P$
   as $P(x) = (x - 1)(x - 2)$ and from here it is clear that the roots are $x_1
   = 1$ and $x_2 = 2$.
2. Let $P(x) = x^2 + 1$. In this case the discriminant $\Delta = -4 < 0$ so the
   polynomial should not have any real roots. We know that this is the case as
   there are no real numbers $x$ such that $x^2 = -1$.
3. Let $P(x) = 0$. The zero polynomial is again special as it has an infinite
   number of roots -- any real number $x$ satisfies $P(x) = 0$.

The above observations are summarized in a theorem, known as the *fundamental
theorem of algebra*, that specifies exactly how many roots a non-zero degree $n$
polynomial with complex coefficients can have.

::: {.theorem}
If $P(x)$ is a non-zero degree $n$ polynomial with complex coefficients, then
$P(x)$ has exactly $n$ complex roots, counted with multiplicity.
:::

As we do not know yet what a complex number is, what this theorem will mean for
us is that an arbitrary non-zero degree $n$ polynomial with real coefficients
will have *at most* $n$ real roots.

::: {.remark}
There are explicit, albeit complicated, formulas for the roots of cubic and
quartic polynomials. By a theorem known as the Abel's impossibility theorem, we
know that there are no solutions in radicals for polynomials of degree $5$ or
higher. This means that we cannot express the roots of those polynomials as
expressions involving addition, subtraction, multiplication, division, raising
to integer powers and taking of n-th roots, as in the quadratic formula. For
example, the simple looking equation

$$
x^5 + x - 1 = 0
$$

cannot be solved in radicals.
:::

## Trigonometric functions

### Trigonometric identities

- Pythagorean identity

$$
\sin^2(\alpha) + \cos^2(\alpha) = 1.
$$

- Sum and difference of angles identities

$$
\begin{align}
\sin(\alpha \pm \beta) &= \sin(\alpha)\cos(\beta) \pm \cos(\beta)\sin(\alpha), \\
\cos(\alpha \pm \beta) &= \cos(\alpha)\cos(\beta) \mp \sin(\alpha)\sin(\beta).
\end{align}
$$

- Double angle identities

$$
\begin{align}
  \sin(2\alpha) &= 2\sin(\alpha)\cos(\alpha) = (\sin(\alpha) + \cos(\alpha))^2 - 1, \\
  \cos(2\alpha) &= \cos^2(\alpha) - \sin^2(\alpha) = 2\cos^2(\alpha) - 1 = 1 - 2\sin^2(\alpha).
\end{align}
$$

- Power reduction identities

$$
\begin{align}
  \sin^2(\alpha) = 1 - \cos^2(\alpha) = \frac{1 - \cos(2\alpha)}{2}, \\
  \cos^2(\alpha) = 1 - \sin^2(\alpha) = \frac{1 + \cos(2\alpha)}{2}
\end{align}
$$
