---
title: "Mathematics for Game Development"
author: "Dimitar Kodjabachev"
site: bookdown::bookdown_site
documentclass: book
output_dir: "docs"
date: "Last updated: `r format(Sys.time(), '%d %B, %Y')`"
---

# {-}

The following is a preliminary list of topics that will be covered in the course
of the lectures. The notes are being updated semi-continuously, so one can
occasionally find them in an incomplete state. In such a case, the curious
reader is advised to try again later.

The mathematical concepts discussed in the lectures are simultaneously
implemented in a C++ library called Aleph zero ($\aleph_0$), whose GitHub
repository can be found [here](https://github.com/dkodjabachev/aleph0).

#### Background material {-}
1. Sets, functions, polynomials
2. Trigonometric functions and identities

#### Linear algebra {-}
1. Algebraic vectors
2. Matrices and matrix operations
3. Determinants and inverse matrices
4. Systems of linear equations

#### Analytic geometry {-}
1. Geometric vectors
2. Coordinate systems, bases and dimension
3. Scalar, cross and triple products of vectors
4. Affine transformations
5. Projections
6. Equations of lines, planes, curves and surfaces
7. Intersection and distance formulas
8. Complex numbers and quaternions

#### Mathematical analysis {-}
1. Derivatives
2. Definite and indefinite integrals

#### Numerical methods {-}
1. Approximation of functions -- splines, B-splines
2. Root-finding algorithms
2. Numerical differentiation and integration
